# Generates NotchBuddy/Resources/Localizable.xcstrings (Spanish translations, English keys).
# Add a line to ES for every new user-visible string, then: python3 scripts/gen-strings.py
import json
ES = {
# status / integrations
"just now":"ahora mismo",
"Not configured · add it in Settings":"Sin configurar · añádelo en Ajustes",
"Checking connection…":"Comprobando conexión…",
"Connected via GitHub CLI":"Conectado con GitHub CLI",
"Connected via GitHub CLI · @%@":"Conectado con GitHub CLI · @%@",
"Connected with token":"Conectado con token",
"GitHub CLI signed out · run gh auth login":"GitHub CLI sin sesión · ejecuta gh auth login",
"Connected, but no pages are shared with the integration":"Conectado, pero no hay páginas compartidas con la integración",
"Connected · %lld recent pages":"Conectado · %lld páginas recientes",
"Connected · no payments yet":"Conectado · aún no hay pagos",
"Connected · no upcoming bookings":"Conectado · no hay reservas próximas",
"Connected · no executions yet":"Conectado · aún no hay ejecuciones",
"Connected · no emails sent yet":"Conectado · aún no se han enviado correos",
"Connected · no deployments yet":"Conectado · aún no hay despliegues",
"Invalid key or no access (%lld)":"Clave no válida o sin acceso (%lld)",
"Can't reach %@ · %@":"No se puede conectar con %@ · %@",
"Can't reach %@":"No se puede conectar con %@",
"Invalid API key (401)":"Clave de API no válida (401)",
"API error %lld":"Error de API %lld",
"Use secret key (sk_live_… not pk_live_…)":"Usa la clave secreta (sk_live_…, no pk_live_…)",
"GitHub CLI request failed · check your connection":"Falló la petición de GitHub CLI · revisa tu conexión",
"Token rejected · check it in Settings":"Token rechazado · revísalo en Ajustes",
"Can't reach GitHub":"No se puede conectar con GitHub",
"GitHub error %lld":"Error de GitHub %lld",
"No API key or URL configured":"No hay clave de API ni URL configuradas",
"No executions found":"No se encontraron ejecuciones",
# approvals
"Low risk":"Riesgo bajo","Medium risk":"Riesgo medio","High risk":"Riesgo alto",
"read only":"solo lectura","external tool":"herramienta externa","unknown tool":"herramienta desconocida",
"sensitive file":"archivo sensible","outside the project":"fuera del proyecto","outside your home folder":"fuera de tu carpeta personal",
"changes a file":"cambia un archivo","deletes files recursively":"borra archivos de forma recursiva","runs as administrator":"se ejecuta como administrador",
"force-pushes":"hace push forzado","discards changes":"descarta cambios","deletes untracked files":"borra archivos sin seguimiento",
"discards work":"descarta trabajo","runs a downloaded script":"ejecuta un script descargado","opens permissions to everyone":"abre permisos a todos",
"writes a disk":"escribe en un disco","deletes data":"borra datos","changes infrastructure":"cambia infraestructura","publishes":"publica",
"kills processes":"mata procesos","deletes files":"borra archivos","installs packages":"instala paquetes","changes the repository":"cambia el repositorio",
"changes files":"cambia archivos","writes a file":"escribe un archivo","uses the network":"usa la red","talks to a service":"habla con un servicio",
"edits files":"edita archivos","reads the repository":"lee el repositorio","builds or tests":"compila o prueba","runs a command":"ejecuta un comando",
"this project, only you":"este proyecto, solo tú","this project, shared with the repo":"este proyecto, compartido en el repo",
"all your projects":"todos tus proyectos","this session":"esta sesión","Claude Code settings":"ajustes de Claude Code",
"Saved for good:":"Se guarda para siempre:","Cancel":"Cancelar","Save rule":"Guardar regla","Deny":"Denegar","Allow":"Permitir","Always…":"Siempre…",
"⌥⌫ deny":"⌥⌫ denegar","⌥⏎ allow · ⌥⌫ deny":"⌥⏎ permitir · ⌥⌫ denegar",
"needs permission":"necesita permiso",
# API errors
"API key missing. Open settings.":"Falta la clave de API. Abre Ajustes.",
"Claude didn't write an answer. Try asking again.":"Claude no escribió una respuesta. Vuelve a preguntar.",
"Anthropic API key missing. Open settings to configure it.":"Falta la clave de API de Anthropic. Abre Ajustes para configurarla.",
"Unexpected API response.":"Respuesta inesperada de la API.",
"Your Anthropic API key was rejected. Check it in Settings → Claude, or switch the chat to your Claude Code subscription.":"Tu clave de API de Anthropic fue rechazada. Revísala en Ajustes → Claude, o cambia el chat a tu suscripción de Claude Code.",
"Your API key can't use the model “%@”. Pick another one in Settings → Model, or switch the chat to your Claude Code subscription.":"Tu clave de API no puede usar el modelo “%@”. Elige otro en Ajustes → Modelo, o cambia el chat a tu suscripción de Claude Code.",
"Your Anthropic API credit balance is too low. Add credits in the Anthropic Console, or switch the chat to your Claude Code subscription.":"Tu saldo de créditos de la API de Anthropic es demasiado bajo. Añade créditos en la Anthropic Console, o cambia el chat a tu suscripción de Claude Code.",
"The API is rate limiting this key. Wait a moment and try again.":"La API está limitando esta clave. Espera un momento y vuelve a intentarlo.",
"Claude is overloaded right now. Try again in a minute.":"Claude está saturado ahora mismo. Vuelve a intentarlo en un minuto.",
"Anthropic's API had a problem (%lld). Try again in a minute.":"La API de Anthropic tuvo un problema (%lld). Vuelve a intentarlo en un minuto.",
"The API answered with an error (%lld).":"La API respondió con un error (%lld).",
"No internet connection. Check your network and try again.":"Sin conexión a internet. Revisa tu red y vuelve a intentarlo.",
"Claude took too long to answer. Try again, or ask for something shorter.":"Claude tardó demasiado en responder. Vuelve a intentarlo o pide algo más corto.",
"Network error: %@":"Error de red: %@",
# island
"• subagent done":"• subagente terminado",
"Live view":"Vista en vivo","Nothing running right now.":"No hay nada en marcha ahora mismo.",
"Drop a file or window, or ask me anything.":"Suelta un archivo o una ventana, o pregúntame lo que quieras.",
"Ask Claude":"Preguntar a Claude","Claude Code is asking a question":"Claude Code está haciendo una pregunta",
"Which search engine to use?":"¿Qué buscador usar?","Workflow stopped.":"El flujo se detuvo.",
"Gmail node timed out after 30s. Retry or open n8n.":"El nodo de Gmail superó el tiempo de 30 s. Reintenta o abre n8n.",
"Retry":"Reintentar","Open in n8n":"Abrir en n8n","Claude Code finished":"Claude Code terminó","Session finished":"Sesión terminada",
"Open terminal":"Abrir terminal","OK":"OK","Too many hits at once.":"Demasiados golpes a la vez.",
"Give me a sec — back to work in three seconds.":"Dame un segundo, vuelvo al trabajo en tres segundos.",
"Drop your files here":"Suelta tus archivos aquí"," is ready.":" está listo.","What do you want to do with it?":"¿Qué quieres hacer con él?",
"Ask a question":"Hacer una pregunta","Send by email":"Enviar por correo","New email":"Nuevo correo","with":"con",
"Missing recipient.":"Falta el destinatario.","Resend error — check API key & sender.":"Error de Resend: revisa la clave de API y el remitente.",
"Set sender address in Settings.":"Configura el remitente en Ajustes.","Mail not available.":"Mail no está disponible.",
"Email sent to %@.":"Correo enviado a %@.",
"Edits on":"Edición activada","Read-only":"Solo lectura",
"Mochi can change files in this project. You approve every change in the island.":"Mochi puede cambiar archivos de este proyecto. Apruebas cada cambio en la isla.",
"Mochi can only read this project. Click to let it propose edits.":"Mochi solo puede leer este proyecto. Haz clic para que pueda proponer cambios.",
"Stop reading aloud":"Dejar de leer en voz alta","Chat history":"Historial de chats","New chat":"Nuevo chat",
"Ask me anything…":"Pregúntame lo que quieras…","Continue…":"Continúa…","Stop and send":"Parar y enviar",
"Talk to Mochi (or hold the push-to-talk shortcut)":"Habla con Mochi (o mantén pulsado el atajo para hablar)",
"Claude is reading %@…":"Claude está leyendo %@…","Claude is searching…":"Claude está buscando…",
"Open":"Abrir","Copy":"Copiar","Close":"Cerrar",
"Hooks installed":"Hooks instalados","Hooks not installed · install them in Settings":"Hooks sin instalar · instálalos en Ajustes",
"Integration":"Integración","Open in %@":"Abrir en %@","Show in Finder":"Mostrar en Finder","Open %@":"Abrir %@",
"Refresh":"Actualizar","Settings…":"Ajustes…","Deployments":"Despliegues","Emails":"Correos","Overview":"Resumen","Payments":"Pagos",
"Schedule":"Agenda","No calls scheduled":"No hay llamadas programadas","Recent":"Recientes","Recent · %lld":"Recientes · %lld",
"No pages shared with your integration yet. In Notion: page → ••• → Connections → add it, then ↻.":"Aún no hay páginas compartidas con tu integración. En Notion: página → ••• → Conexiones → añádela y pulsa ↻.",
"Completed successfully.":"Completado correctamente.","No error details available.":"No hay detalles del error.",
"Sound":"Sonido","Auto-close · %llds":"Cierre automático · %lld s",
"resets in ":"se reinicia en ","resets ":"se reinicia ","Week":"Semana","Context":"Contexto","/compact soon":"/compact pronto",
"Hooks installed · usage shows after your next Claude message":"Hooks instalados · el uso aparece tras tu próximo mensaje a Claude",
"Hooks installed · update them in Settings to see plan usage":"Hooks instalados · actualízalos en Ajustes para ver el uso del plan",
"No saved chats yet":"Aún no hay chats guardados",
"Conversations with Mochi are kept here so you can pick them up later.":"Las conversaciones con Mochi se guardan aquí para retomarlas más tarde.",
"%lld saved · last %lld kept":"%lld guardados · se conservan los últimos %lld",
"Clear all":"Borrar todo","Delete this chat":"Borrar este chat","Listening…":"Escuchando…","Transcribing…":"Transcribiendo…",
"Coucou needs Accessibility permission to read the file you're editing. Settings → Hotkey → Grant access.":"Coucou necesita el permiso de Accesibilidad para leer el archivo que editas. Ajustes → Atajo → Dar acceso.",
"new file":"archivo nuevo","+1 more edit":"+1 cambio más","+%lld more edits":"+%lld cambios más","diff truncated":"diff recortado",
"Waiting for Claude…":"Esperando a Claude…","Done · 1 step":"Listo · 1 paso","Done · %lld steps":"Listo · %lld pasos","Working…":"Trabajando…",
"Ask Mochi":"Preguntar a Mochi","Ask about this change in the chat":"Pregunta por este cambio en el chat",
"Open the file in your editor":"Abre el archivo en tu editor","Back":"Volver",
"Uploading %@":"Subiendo %@","%@ is ready.":"%@ está listo.","Ask a question about it":"Hacer una pregunta sobre él",
# settings
"Same as the Mac":"Igual que el Mac","Chat":"Chat","Engine":"Motor","Claude Code (subscription)":"Claude Code (suscripción)",
"Anthropic API key":"Clave de API de Anthropic","Claude Code found: %@":"Claude Code encontrado: %@",
"Claude Code not found. Install it and sign in, then check again.":"No se encontró Claude Code. Instálalo, inicia sesión y vuelve a comprobar.",
"Check again":"Volver a comprobar",
"Uses your Claude Code sign-in and plan limits — no API key needed. The chat can only search the web and read files you drop on the island.":"Usa tu sesión de Claude Code y los límites de tu plan, sin clave de API. El chat solo puede buscar en la web y leer archivos que sueltes en la isla.",
"API key (sk-ant-…)":"Clave de API (sk-ant-…)","Save":"Guardar","✓ Key saved.":"✓ Clave guardada.","Model":"Modelo","Custom…":"Personalizado…",
"Model ID (e.g. claude-opus-5-5)":"ID del modelo (p. ej. claude-opus-5-5)",
"Used by the chat. Fable needs access on your plan or API account.":"Lo usa el chat. Fable necesita acceso en tu plan o cuenta de API.",
"Longest answer":"Respuesta más larga","Short (1,024 tokens)":"Corta (1.024 tokens)","Medium (2,048)":"Media (2.048)","Long (4,096)":"Larga (4.096)",
"Very long (8,192)":"Muy larga (8.192)","Maximum (16,000)":"Máxima (16.000)",
"Caps how much each API answer can write. Longer answers cost more tokens.":"Limita cuánto puede escribir cada respuesta de la API. Las respuestas largas gastan más tokens.",
"Claude Code Hooks":"Hooks de Claude Code","Hooks need an update (approvals timeout / plan usage bars)":"Los hooks necesitan una actualización (tiempo de aprobaciones / barras de uso del plan)",
"Update hooks":"Actualizar hooks","Install hooks":"Instalar hooks","Uninstall":"Desinstalar",
"Choose your ~/.claude folder so Coucou can add its hooks.":"Elige tu carpeta ~/.claude para que Coucou añada sus hooks.",
"Choose .claude folder…":"Elegir carpeta .claude…","Confirm & write":"Confirmar y escribir",
"No supported editor found. Projects open in Finder.":"No se encontró un editor compatible. Los proyectos se abren en Finder.",
"Open projects in":"Abrir proyectos en","Integrations":"Integraciones","API key  (re_…)":"Clave de API  (re_…)",
"From address  (you@yourdomain.com)":"Remitente  (tu@tudominio.com)","Instance URL  (https://…)":"URL de la instancia  (https://…)",
"API key":"Clave de API","Token":"Token","Test connection":"Probar conexión",
"Personal Access Token (not needed while gh is signed in)":"Personal Access Token (no hace falta con gh iniciado)",
"Personal Access Token":"Personal Access Token","Secret key  (sk_live_… or sk_test_…)":"Clave secreta  (sk_live_… o sk_test_…)",
"API key  (cal_live_…)":"Clave de API  (cal_live_…)","Integration token  (secret_…)":"Token de integración  (secret_…)",
"Save integrations":"Guardar integraciones","Enable sounds":"Activar sonidos","Volume":"Volumen","Behavior":"Comportamiento",
"Close after":"Cerrar tras","s inactive":"s de inactividad","Hide after":"Ocultar tras","min without movement":"min sin movimiento",
"Active pills":"Pastillas activas","Always active":"Siempre activa","%lld/4 slots used":"%lld/4 huecos usados","Hotkey":"Atajo",
"Show island with shortcut":"Mostrar la isla con un atajo","Shortcut":"Atajo","presses this → island opens":"al pulsarlo → se abre la isla",
"Ask Mochi about the file you're editing":"Preguntar a Mochi por el archivo que editas","attaches the open file + selection":"adjunta el archivo abierto + la selección",
"Mochi can read and search that project but never edits it.":"Mochi puede leer y buscar en ese proyecto, pero nunca lo edita.",
"Accessibility access granted":"Acceso de Accesibilidad concedido","Accessibility access needed to read the open file":"Hace falta acceso de Accesibilidad para leer el archivo abierto",
"Grant access…":"Dar acceso…","Check":"Comprobar","Approve from the keyboard: ⌥⏎ Allow · ⌥⌫ Deny":"Aprobar con el teclado: ⌥⏎ Permitir · ⌥⌫ Denegar",
"Only active while Claude Code is waiting for you. High-risk requests need a click on Allow.":"Solo funciona mientras Claude Code te espera. Las peticiones de riesgo alto necesitan un clic en Permitir.",
"Push-to-talk: hold to talk to Mochi":"Pulsar para hablar: mantén pulsado para hablar con Mochi","hold, speak, let go → sent":"mantén, habla, suelta → se envía",
"Language":"Idioma","Read Mochi's answers aloud":"Leer en voz alta las respuestas de Mochi",
"Speech is transcribed on this Mac when it supports it. Mochi only listens while you hold the shortcut.":"La voz se transcribe en este Mac cuando lo admite. Mochi solo escucha mientras mantienes pulsado el atajo.",
"Microphone and Speech Recognition allowed":"Micrófono y Reconocimiento de voz permitidos",
"macOS asks for Microphone and Speech Recognition the first time":"macOS pide Micrófono y Reconocimiento de voz la primera vez",
"Allow now…":"Permitir ahora…","Interface":"Interfaz","Restart Coucou to apply the new language.":"Reinicia Coucou para aplicar el nuevo idioma.",
"Restart now":"Reiniciar ahora","Startup":"Inicio","Launch at Mac startup":"Abrir al iniciar el Mac",
"Connected via GitHub CLI — @%@. No token needed.":"Conectado con GitHub CLI — @%@. No hace falta token.",
"Connected via GitHub CLI. No token needed.":"Conectado con GitHub CLI. No hace falta token.",
"Connected with your Personal Access Token.":"Conectado con tu Personal Access Token.","Looking for the GitHub CLI…":"Buscando GitHub CLI…",
"Using GitHub CLI — signed in as @%@":"Usando GitHub CLI — sesión iniciada como @%@","Using GitHub CLI (signed in). No token needed.":"Usando GitHub CLI (sesión iniciada). No hace falta token.",
"GitHub CLI found but signed out. Run `gh auth login`, or paste a token.":"GitHub CLI está instalado pero sin sesión. Ejecuta `gh auth login` o pega un token.",
"GitHub CLI not found. Install it (brew install gh) and sign in, or paste a token.":"No se encontró GitHub CLI. Instálalo (brew install gh) e inicia sesión, o pega un token.",
"Choose your .claude folder so Coucou can add its hooks":"Elige tu carpeta .claude para que Coucou añada sus hooks",
"✓ .claude folder access granted.":"✓ Acceso a la carpeta .claude concedido.","❌ Bookmark error: %@":"❌ Error de marcador: %@",
"❌ .claude folder access lost — choose the folder again.":"❌ Se perdió el acceso a la carpeta .claude: vuelve a elegirla.",
"Review the JSON below before confirming.":"Revisa el JSON de abajo antes de confirmar.","❌ .claude folder access lost.":"❌ Se perdió el acceso a la carpeta .claude.",
"✓ Hooks installed in ~/.claude/settings.json":"✓ Hooks instalados en ~/.claude/settings.json","❌ Write error: %@":"❌ Error al escribir: %@",
"✓ Hooks removed.":"✓ Hooks eliminados.","✓ Integration keys saved.":"✓ Claves de integraciones guardadas.",
"❌ Save Vercel token first.":"❌ Guarda primero el token de Vercel.","❌ No Vercel projects found.":"❌ No se encontraron proyectos de Vercel.",
"❌ Save n8n URL and API key first.":"❌ Guarda primero la URL y la clave de API de n8n.","❌ No n8n workflows found.":"❌ No se encontraron flujos de n8n.",
"Load list":"Cargar lista","Clear":"Borrar","Watching %lld of %lld":"Siguiendo %lld de %lld","Press keys…":"Pulsa las teclas…",
"Coucou needs the microphone for push-to-talk. System Settings → Privacy & Security → Microphone.":"Coucou necesita el micrófono para hablar. Ajustes del Sistema → Privacidad y seguridad → Micrófono.",
"Coucou needs Speech Recognition for push-to-talk. System Settings → Privacy & Security → Speech Recognition.":"Coucou necesita Reconocimiento de voz para hablar. Ajustes del Sistema → Privacidad y seguridad → Reconocimiento de voz.",
"Speech recognition isn't available for %@ on this Mac.":"El reconocimiento de voz no está disponible para %@ en este Mac.",
# do not disturb
"Do not disturb":"No molestar","Turn off Do not disturb":"Desactivar No molestar","For 1 hour":"Durante 1 hora",
"Until tomorrow morning":"Hasta mañana por la mañana","Until I turn it off":"Hasta que lo desactive",
"During calendar events":"Durante eventos del calendario","On until you turn it off":"Activado hasta que lo desactives",
"On until %@":"Activado hasta las %@","On during your calendar event":"Activado durante tu evento del calendario",
"Do not disturb: no sounds, the island doesn't open by itself":"No molestar: sin sonidos y la isla no se abre sola",
"Automatically during calendar events":"Automáticamente durante eventos del calendario",
"Calendar access granted":"Acceso al calendario concedido",
"Coucou needs access to your calendars to see when you're in a meeting":"Coucou necesita acceso a tus calendarios para saber cuándo estás en una reunión",
"Allow calendar access…":"Permitir acceso al calendario…",
"No sounds, and the island doesn't open by itself: finished, failed and approval events only badge the pill. Also in the 🌙 menu on the island.":"Sin sonidos y la isla no se abre sola: lo terminado, los fallos y las aprobaciones solo marcan la pastilla. También en el menú 🌙 de la isla.",
# session timeline
"Timeline":"Cronología","Everything Claude did in this session, with times":"Todo lo que hizo Claude en esta sesión, con horas",
"Session started":"Sesión iniciada","You asked":"Preguntaste","Turn finished":"Turno terminado","Turn failed":"El turno falló",
"You allowed":"Permitiste","You always allowed":"Permitiste siempre","You denied":"Denegaste","Not answered in time":"Sin respuesta a tiempo",
"%lld files read":"%lld archivos leídos","%lld edits":"%lld cambios","%lld commands":"%lld comandos","%lld approvals":"%lld aprobaciones",
"Read":"Leyó","Edited":"Editó","Wrote":"Escribió","Ran":"Ejecutó","Searched":"Buscó","Searched the web":"Buscó en la web",
"Opened":"Abrió","Subagent":"Subagente","Nothing yet. Claude Code's steps for this session show up here.":"Nada todavía. Aquí aparecen los pasos de Claude Code en esta sesión.",
"Copied":"Copiado","Copy as Markdown":"Copiar como Markdown","Back to the diff":"Volver al diff",
# auto-approve
"Ask every time":"Preguntar siempre","Auto-allow low risk":"Permitir solo el riesgo bajo","Auto-allow low and medium risk":"Permitir riesgo bajo y medio",
"Auto-allowed":"Permitido automáticamente","In %@":"En %@","Auto-approve in this project (never high risk)":"Aprobar automáticamente en este proyecto (nunca riesgo alto)",
"Auto-approve (Claude Code)":"Aprobación automática (Claude Code)",
"Coucou can answer Allow for you, per project. High-risk requests always ask. Auto-allowed steps show in the session timeline.":"Coucou puede responder Permitir por ti, por proyecto. Las peticiones de riesgo alto siempre preguntan. Lo permitido automáticamente aparece en la cronología.",
"Projects appear here once Claude Code runs in them (or set it from ⚡ on an approval).":"Los proyectos aparecen aquí cuando Claude Code trabaja en ellos (o configúralo desde ⚡ en una aprobación).",
# phone alerts
"Phone alerts":"Avisos al móvil","Send approvals that wait 20 s to my phone":"Enviar al móvil las aprobaciones que esperan 20 s",
"Only when I'm away (screen locked or 2 min idle)":"Solo cuando no estoy (pantalla bloqueada o 2 min sin actividad)",
"Topic":"Tema","New":"Nuevo","Server":"Servidor","Send test":"Enviar prueba",
"Install the free ntfy app (iOS / Android), tap + and subscribe to this topic. The alert includes the project and the command: keep the topic private, or use your own ntfy server.":"Instala la app gratuita ntfy (iOS / Android), pulsa + y suscríbete a este tema. El aviso incluye el proyecto y el comando: mantén el tema en privado o usa tu propio servidor ntfy.",
"Claude Code needs you · %@":"Claude Code te necesita · %@","Coucou is connected":"Coucou está conectado",
"You'll get approvals here when you're away from the Mac.":"Aquí recibirás las aprobaciones cuando no estés en el Mac.",
# linear
"Add your Linear API key in Settings":"Añade tu clave de API de Linear en Ajustes","Can't reach Linear":"No se puede conectar con Linear",
"Linear didn't accept the comment":"Linear no aceptó el comentario","Connected · nothing assigned to you":"Conectado · no tienes nada asignado",
"Connected · %lld open issues":"Conectado · %lld issues abiertas","Assigned to you":"Asignadas a ti","Assigned to you · %lld":"Asignadas a ti · %lld",
"Nothing open is assigned to you.":"No tienes nada abierto asignado.","A Claude Code session is working on it":"Una sesión de Claude Code está trabajando en ella",
"Open in Linear":"Abrir en Linear","Copy branch name":"Copiar nombre de la rama","Copy identifier":"Copiar identificador",
"Personal API key  (lin_api_…)":"Clave de API personal  (lin_api_…)",
"Linear → Settings → Security & access → Personal API keys. Shows your open issues and links each Claude Code session to the issue in its branch name.":"Linear → Settings → Security & access → Personal API keys. Muestra tus issues abiertas y vincula cada sesión de Claude Code con la issue de su rama.",
"Posted to %@":"Publicado en %@","Posting…":"Publicando…","Post to %@":"Publicar en %@",
"Add this timeline as a comment on %@ · %@":"Añadir esta cronología como comentario en %@ · %@",
# inbox
"Review requested":"Te pidieron review","Mentioned you":"Te mencionaron","Assignment":"Asignación","New comment":"Comentario nuevo","Update":"Novedad",
"Inbox: nothing waiting for you":"Bandeja: nada pendiente","Inbox: %lld waiting for you":"Bandeja: %lld pendientes","Inbox":"Bandeja",
"Mark all read":"Marcar todo leído","Mark as read":"Marcar como leído",
"Nothing waiting for you. Review requests, mentions and assignments from GitHub and Linear show up here.":"Nada pendiente. Aquí aparecen las peticiones de review, menciones y asignaciones de GitHub y Linear.",
"Mochi tells me when someone needs me":"Mochi me avisa cuando alguien me necesita","GitHub (through gh)":"GitHub (con gh)",
"Reviews":"Reviews","Mentions":"Menciones","Assigned":"Asignaciones","Comments":"Comentarios","Other":"Otros",
"Checked every minute. New items make Mochi peek out (only a badge in Do not disturb); the 🔔 in the island lists them. Opening or dismissing one marks it read on GitHub / Linear.":"Se revisa cada minuto. Lo nuevo hace que Mochi se asome (solo una marca en No molestar); la 🔔 de la isla lo lista. Abrir o descartar algo lo marca como leído en GitHub / Linear.",
"%lld new notifications. Latest, %@":"%lld notificaciones nuevas. La última, %@","Mochi says it out loud":"Mochi lo dice en voz alta","Try it":"Probar",
}
catalog = {"sourceLanguage": "en", "version": "1.0", "strings": {
    k: {"localizations": {"es": {"stringUnit": {"state": "translated", "value": v}}}} for k, v in sorted(ES.items())
}}
import os
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "NotchBuddy", "Resources", "Localizable.xcstrings")
with open(path, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
print(len(ES), "strings")
