# Generates NotchBuddy/Resources/Localizable.xcstrings (Spanish translations, English keys).
# Add a line to ES for every new user-visible string, then: python3 scripts/gen-strings.py
import json
ES = {
# status / integrations
"just now":"ahora mismo",
"Not configured · add it in Settings":"Sin configurar · añádelo en Ajustes",
"Checking connection…":"Comprobando conexión…",
"Connected via GitHub CLI":"Conectado con GitHub CLI",
"Connected via GitHub CLI · @%@":"Conectado con GitHub CLI · @%@",
"Connected with token":"Conectado con token",
"GitHub CLI signed out · run gh auth login":"GitHub CLI sin sesión · ejecuta gh auth login",
"Connected, but no pages are shared with the integration":"Conectado, pero no hay páginas compartidas con la integración",
"Connected · %lld recent pages":"Conectado · %lld páginas recientes",
"Connected · no payments yet":"Conectado · aún no hay pagos",
"Connected · no upcoming bookings":"Conectado · no hay reservas próximas",
"Connected · no executions yet":"Conectado · aún no hay ejecuciones",
"Connected · no emails sent yet":"Conectado · aún no se han enviado correos",
"Connected · no deployments yet":"Conectado · aún no hay despliegues",
"Invalid key or no access (%lld)":"Clave no válida o sin acceso (%lld)",
"Can't reach %@ · %@":"No se puede conectar con %@ · %@",
"Can't reach %@":"No se puede conectar con %@",
"Invalid API key (401)":"Clave de API no válida (401)",
"API error %lld":"Error de API %lld",
"Use secret key (sk_live_… not pk_live_…)":"Usa la clave secreta (sk_live_…, no pk_live_…)",
"GitHub CLI request failed · check your connection":"Falló la petición de GitHub CLI · revisa tu conexión",
"Token rejected · check it in Settings":"Token rechazado · revísalo en Ajustes",
"Can't reach GitHub":"No se puede conectar con GitHub",
"GitHub error %lld":"Error de GitHub %lld",
"No API key or URL configured":"No hay clave de API ni URL configuradas",
"No executions found":"No se encontraron ejecuciones",
# approvals
"Low risk":"Riesgo bajo","Medium risk":"Riesgo medio","High risk":"Riesgo alto",
"read only":"solo lectura","external tool":"herramienta externa","unknown tool":"herramienta desconocida",
"sensitive file":"archivo sensible","outside the project":"fuera del proyecto","outside your home folder":"fuera de tu carpeta personal",
"changes a file":"cambia un archivo","deletes files recursively":"borra archivos de forma recursiva","runs as administrator":"se ejecuta como administrador",
"force-pushes":"hace push forzado","discards changes":"descarta cambios","deletes untracked files":"borra archivos sin seguimiento",
"discards work":"descarta trabajo","runs a downloaded script":"ejecuta un script descargado","opens permissions to everyone":"abre permisos a todos",
"writes a disk":"escribe en un disco","deletes data":"borra datos","changes infrastructure":"cambia infraestructura","publishes":"publica",
"kills processes":"mata procesos","deletes files":"borra archivos","installs packages":"instala paquetes","changes the repository":"cambia el repositorio",
"changes files":"cambia archivos","writes a file":"escribe un archivo","uses the network":"usa la red","talks to a service":"habla con un servicio",
"edits files":"edita archivos","reads the repository":"lee el repositorio","builds or tests":"compila o prueba","runs a command":"ejecuta un comando",
"this project, only you":"este proyecto, solo tú","this project, shared with the repo":"este proyecto, compartido en el repo",
"all your projects":"todos tus proyectos","this session":"esta sesión","Claude Code settings":"ajustes de Claude Code",
"Saved for good:":"Se guarda para siempre:","Cancel":"Cancelar","Save rule":"Guardar regla","Deny":"Denegar","Allow":"Permitir","Always…":"Siempre…",
"⌥⌫ deny":"⌥⌫ denegar","⌥⏎ allow · ⌥⌫ deny":"⌥⏎ permitir · ⌥⌫ denegar",
"needs permission":"necesita permiso",
# API errors
"API key missing. Open settings.":"Falta la clave de API. Abre Ajustes.",
"Claude didn't write an answer. Try asking again.":"Claude no escribió una respuesta. Vuelve a preguntar.",
"Anthropic API key missing. Open settings to configure it.":"Falta la clave de API de Anthropic. Abre Ajustes para configurarla.",
"Unexpected API response.":"Respuesta inesperada de la API.",
"Your Anthropic API key was rejected. Check it in Settings → Claude, or switch the chat to your Claude Code subscription.":"Tu clave de API de Anthropic fue rechazada. Revísala en Ajustes → Claude, o cambia el chat a tu suscripción de Claude Code.",
"Your API key can't use the model “%@”. Pick another one in Settings → Model, or switch the chat to your Claude Code subscription.":"Tu clave de API no puede usar el modelo “%@”. Elige otro en Ajustes → Modelo, o cambia el chat a tu suscripción de Claude Code.",
"Your Anthropic API credit balance is too low. Add credits in the Anthropic Console, or switch the chat to your Claude Code subscription.":"Tu saldo de créditos de la API de Anthropic es demasiado bajo. Añade créditos en la Anthropic Console, o cambia el chat a tu suscripción de Claude Code.",
"The API is rate limiting this key. Wait a moment and try again.":"La API está limitando esta clave. Espera un momento y vuelve a intentarlo.",
"Claude is overloaded right now. Try again in a minute.":"Claude está saturado ahora mismo. Vuelve a intentarlo en un minuto.",
"Anthropic's API had a problem (%lld). Try again in a minute.":"La API de Anthropic tuvo un problema (%lld). Vuelve a intentarlo en un minuto.",
"The API answered with an error (%lld).":"La API respondió con un error (%lld).",
"No internet connection. Check your network and try again.":"Sin conexión a internet. Revisa tu red y vuelve a intentarlo.",
"Claude took too long to answer. Try again, or ask for something shorter.":"Claude tardó demasiado en responder. Vuelve a intentarlo o pide algo más corto.",
"Network error: %@":"Error de red: %@",
# island
"• subagent done":"• subagente terminado",
"Live view":"Vista en vivo","Nothing running right now.":"No hay nada en marcha ahora mismo.",
"Drop a file or window, or ask me anything.":"Suelta un archivo o una ventana, o pregúntame lo que quieras.",
"Ask Claude":"Preguntar a Claude","Claude Code is asking a question":"Claude Code está haciendo una pregunta",
"Which search engine to use?":"¿Qué buscador usar?","Workflow stopped.":"El flujo se detuvo.",
"Gmail node timed out after 30s. Retry or open n8n.":"El nodo de Gmail superó el tiempo de 30 s. Reintenta o abre n8n.",
"Retry":"Reintentar","Open in n8n":"Abrir en n8n","Claude Code finished":"Claude Code terminó","Session finished":"Sesión terminada",
"Open terminal":"Abrir terminal","OK":"OK","Too many hits at once.":"Demasiados golpes a la vez.",
"Give me a sec — back to work in three seconds.":"Dame un segundo, vuelvo al trabajo en tres segundos.",
"Drop your files here":"Suelta tus archivos aquí"," is ready.":" está listo.","What do you want to do with it?":"¿Qué quieres hacer con él?",
"Ask a question":"Hacer una pregunta","Send by email":"Enviar por correo","New email":"Nuevo correo","with":"con",
"Missing recipient.":"Falta el destinatario.","Resend error — check API key & sender.":"Error de Resend: revisa la clave de API y el remitente.",
"Set sender address in Settings.":"Configura el remitente en Ajustes.","Mail not available.":"Mail no está disponible.",
"Email sent to %@.":"Correo enviado a %@.",
"Edits on":"Edición activada","Read-only":"Solo lectura",
"Mochi can change files in this project. You approve every change in the island.":"Mochi puede cambiar archivos de este proyecto. Apruebas cada cambio en la isla.",
"Mochi can only read this project. Click to let it propose edits.":"Mochi solo puede leer este proyecto. Haz clic para que pueda proponer cambios.",
"Stop reading aloud":"Dejar de leer en voz alta","Chat history":"Historial de chats","New chat":"Nuevo chat",
"Ask me anything…":"Pregúntame lo que quieras…","Continue…":"Continúa…","Stop and send":"Parar y enviar",
"Talk to Mochi (or hold the push-to-talk shortcut)":"Habla con Mochi (o mantén pulsado el atajo para hablar)",
"Claude is reading %@…":"Claude está leyendo %@…","Claude is searching…":"Claude está buscando…",
"Open":"Abrir","Copy":"Copiar","Close":"Cerrar",
"Hooks installed":"Hooks instalados","Hooks not installed · install them in Settings":"Hooks sin instalar · instálalos en Ajustes",
"Integration":"Integración","Open in %@":"Abrir en %@","Show in Finder":"Mostrar en Finder","Open %@":"Abrir %@",
"Refresh":"Actualizar","Settings…":"Ajustes…","Deployments":"Despliegues","Emails":"Correos","Overview":"Resumen","Payments":"Pagos",
"Schedule":"Agenda","No calls scheduled":"No hay llamadas programadas","Recent":"Recientes","Recent · %lld":"Recientes · %lld",
"No pages shared with your integration yet. In Notion: page → ••• → Connections → add it, then ↻.":"Aún no hay páginas compartidas con tu integración. En Notion: página → ••• → Conexiones → añádela y pulsa ↻.",
"Completed successfully.":"Completado correctamente.","No error details available.":"No hay detalles del error.",
"Sound":"Sonido","Auto-close · %llds":"Cierre automático · %lld s",
"resets in ":"se reinicia en ","resets ":"se reinicia ","Week":"Semana","Context":"Contexto","/compact soon":"/compact pronto",
"Hooks installed · usage shows after your next Claude message":"Hooks instalados · el uso aparece tras tu próximo mensaje a Claude",
"Hooks installed · update them in Settings to see plan usage":"Hooks instalados · actualízalos en Ajustes para ver el uso del plan",
"No saved chats yet":"Aún no hay chats guardados",
"Conversations with Mochi are kept here so you can pick them up later.":"Las conversaciones con Mochi se guardan aquí para retomarlas más tarde.",
"%lld saved · last %lld kept":"%lld guardados · se conservan los últimos %lld",
"Clear all":"Borrar todo","Delete this chat":"Borrar este chat","Listening…":"Escuchando…","Transcribing…":"Transcribiendo…",
"Coucou needs Accessibility permission to read the file you're editing. Settings → Hotkey → Grant access.":"Coucou necesita el permiso de Accesibilidad para leer el archivo que editas. Ajustes → Atajo → Dar acceso.",
"new file":"archivo nuevo","+1 more edit":"+1 cambio más","+%lld more edits":"+%lld cambios más","diff truncated":"diff recortado",
"Waiting for Claude…":"Esperando a Claude…","Done · 1 step":"Listo · 1 paso","Done · %lld steps":"Listo · %lld pasos","Working…":"Trabajando…",
"Ask Mochi":"Preguntar a Mochi","Ask about this change in the chat":"Pregunta por este cambio en el chat",
"Open the file in your editor":"Abre el archivo en tu editor","Back":"Volver",
"Uploading %@":"Subiendo %@","%@ is ready.":"%@ está listo.","Ask a question about it":"Hacer una pregunta sobre él",
# settings
"Same as the Mac":"Igual que el Mac","Chat":"Chat","Engine":"Motor","Claude Code (subscription)":"Claude Code (suscripción)",
"Anthropic API key":"Clave de API de Anthropic","Claude Code found: %@":"Claude Code encontrado: %@",
"Claude Code not found. Install it and sign in, then check again.":"No se encontró Claude Code. Instálalo, inicia sesión y vuelve a comprobar.",
"Check again":"Volver a comprobar",
"Uses your Claude Code sign-in and plan limits — no API key needed. The chat can only search the web and read files you drop on the island.":"Usa tu sesión de Claude Code y los límites de tu plan, sin clave de API. El chat solo puede buscar en la web y leer archivos que sueltes en la isla.",
"API key (sk-ant-…)":"Clave de API (sk-ant-…)","Save":"Guardar","✓ Key saved.":"✓ Clave guardada.","Model":"Modelo","Custom…":"Personalizado…",
"Model ID (e.g. claude-opus-5-5)":"ID del modelo (p. ej. claude-opus-5-5)",
"Used by the chat. Fable needs access on your plan or API account.":"Lo usa el chat. Fable necesita acceso en tu plan o cuenta de API.",
"Longest answer":"Respuesta más larga","Short (1,024 tokens)":"Corta (1.024 tokens)","Medium (2,048)":"Media (2.048)","Long (4,096)":"Larga (4.096)",
"Very long (8,192)":"Muy larga (8.192)","Maximum (16,000)":"Máxima (16.000)",
"Caps how much each API answer can write. Longer answers cost more tokens.":"Limita cuánto puede escribir cada respuesta de la API. Las respuestas largas gastan más tokens.",
"Claude Code Hooks":"Hooks de Claude Code","Hooks need an update (approvals timeout / plan usage bars)":"Los hooks necesitan una actualización (tiempo de aprobaciones / barras de uso del plan)",
"Update hooks":"Actualizar hooks","Install hooks":"Instalar hooks","Uninstall":"Desinstalar",
"Choose your ~/.claude folder so Coucou can add its hooks.":"Elige tu carpeta ~/.claude para que Coucou añada sus hooks.",
"Choose .claude folder…":"Elegir carpeta .claude…","Confirm & write":"Confirmar y escribir",
"No supported editor found. Projects open in Finder.":"No se encontró un editor compatible. Los proyectos se abren en Finder.",
"Open projects in":"Abrir proyectos en","Integrations":"Integraciones","API key  (re_…)":"Clave de API  (re_…)",
"From address  (you@yourdomain.com)":"Remitente  (tu@tudominio.com)","Instance URL  (https://…)":"URL de la instancia  (https://…)",
"API key":"Clave de API","Token":"Token","Test connection":"Probar conexión",
"Personal Access Token (not needed while gh is signed in)":"Personal Access Token (no hace falta con gh iniciado)",
"Personal Access Token":"Personal Access Token","Secret key  (sk_live_… or sk_test_…)":"Clave secreta  (sk_live_… o sk_test_…)",
"API key  (cal_live_…)":"Clave de API  (cal_live_…)","Integration token  (secret_…)":"Token de integración  (secret_…)",
"Save integrations":"Guardar integraciones","Enable sounds":"Activar sonidos","Volume":"Volumen","Behavior":"Comportamiento",
"Close after":"Cerrar tras","s inactive":"s de inactividad","Hide after":"Ocultar tras","min without movement":"min sin movimiento",
"Active pills":"Pastillas activas","Always active":"Siempre activa","%lld active · the island shows 4 at a time":"%lld activas · la isla muestra 4 a la vez","Rotate the rest":"Rotar las demás","Off":"Desactivado","Every 10 s":"Cada 10 s","Every 30 s":"Cada 30 s","Every minute":"Cada minuto","Hotkey":"Atajo",
"Show island with shortcut":"Mostrar la isla con un atajo","Shortcut":"Atajo","presses this → island opens":"al pulsarlo → se abre la isla",
"Ask Mochi about the file you're editing":"Preguntar a Mochi por el archivo que editas","attaches the open file + selection":"adjunta el archivo abierto + la selección",
"Mochi can read and search that project but never edits it.":"Mochi puede leer y buscar en ese proyecto, pero nunca lo edita.",
"Accessibility access granted":"Acceso de Accesibilidad concedido","Accessibility access needed to read the open file":"Hace falta acceso de Accesibilidad para leer el archivo abierto",
"Grant access…":"Dar acceso…","Check":"Comprobar","Approve from the keyboard: ⌥⏎ Allow · ⌥⌫ Deny":"Aprobar con el teclado: ⌥⏎ Permitir · ⌥⌫ Denegar",
"Only active while Claude Code is waiting for you. High-risk requests need a click on Allow.":"Solo funciona mientras Claude Code te espera. Las peticiones de riesgo alto necesitan un clic en Permitir.",
"Push-to-talk: hold to talk to Mochi":"Pulsar para hablar: mantén pulsado para hablar con Mochi","hold, speak, let go → sent":"mantén, habla, suelta → se envía",
"Language":"Idioma","Read Mochi's answers aloud":"Leer en voz alta las respuestas de Mochi",
"Speech is transcribed on this Mac when it supports it. Mochi only listens while you hold the shortcut.":"La voz se transcribe en este Mac cuando lo admite. Mochi solo escucha mientras mantienes pulsado el atajo.",
"Microphone and Speech Recognition allowed":"Micrófono y Reconocimiento de voz permitidos",
"macOS asks for Microphone and Speech Recognition the first time":"macOS pide Micrófono y Reconocimiento de voz la primera vez",
"Allow now…":"Permitir ahora…","Interface":"Interfaz","Restart Coucou to apply the new language.":"Reinicia Coucou para aplicar el nuevo idioma.",
"Restart now":"Reiniciar ahora","Startup":"Inicio","Launch at Mac startup":"Abrir al iniciar el Mac",
"Connected via GitHub CLI — @%@. No token needed.":"Conectado con GitHub CLI — @%@. No hace falta token.",
"Connected via GitHub CLI. No token needed.":"Conectado con GitHub CLI. No hace falta token.",
"Connected with your Personal Access Token.":"Conectado con tu Personal Access Token.","Looking for the GitHub CLI…":"Buscando GitHub CLI…",
"Using GitHub CLI — signed in as @%@":"Usando GitHub CLI — sesión iniciada como @%@","Using GitHub CLI (signed in). No token needed.":"Usando GitHub CLI (sesión iniciada). No hace falta token.",
"GitHub CLI found but signed out. Run `gh auth login`, or paste a token.":"GitHub CLI está instalado pero sin sesión. Ejecuta `gh auth login` o pega un token.",
"GitHub CLI not found. Install it (brew install gh) and sign in, or paste a token.":"No se encontró GitHub CLI. Instálalo (brew install gh) e inicia sesión, o pega un token.",
"Choose your .claude folder so Coucou can add its hooks":"Elige tu carpeta .claude para que Coucou añada sus hooks",
"✓ .claude folder access granted.":"✓ Acceso a la carpeta .claude concedido.","❌ Bookmark error: %@":"❌ Error de marcador: %@",
"❌ .claude folder access lost — choose the folder again.":"❌ Se perdió el acceso a la carpeta .claude: vuelve a elegirla.",
"Review the JSON below before confirming.":"Revisa el JSON de abajo antes de confirmar.","❌ .claude folder access lost.":"❌ Se perdió el acceso a la carpeta .claude.",
"✓ Hooks installed in ~/.claude/settings.json":"✓ Hooks instalados en ~/.claude/settings.json","❌ Write error: %@":"❌ Error al escribir: %@",
"✓ Hooks removed.":"✓ Hooks eliminados.","✓ Integration keys saved.":"✓ Claves de integraciones guardadas.",
"❌ Save Vercel token first.":"❌ Guarda primero el token de Vercel.","❌ No Vercel projects found.":"❌ No se encontraron proyectos de Vercel.",
"❌ Save n8n URL and API key first.":"❌ Guarda primero la URL y la clave de API de n8n.","❌ No n8n workflows found.":"❌ No se encontraron flujos de n8n.",
"Load list":"Cargar lista","Clear":"Borrar","Watching %lld of %lld":"Siguiendo %lld de %lld","Press keys…":"Pulsa las teclas…",
"Coucou needs the microphone for push-to-talk. System Settings → Privacy & Security → Microphone.":"Coucou necesita el micrófono para hablar. Ajustes del Sistema → Privacidad y seguridad → Micrófono.",
"Coucou needs Speech Recognition for push-to-talk. System Settings → Privacy & Security → Speech Recognition.":"Coucou necesita Reconocimiento de voz para hablar. Ajustes del Sistema → Privacidad y seguridad → Reconocimiento de voz.",
"Speech recognition isn't available for %@ on this Mac.":"El reconocimiento de voz no está disponible para %@ en este Mac.",
# do not disturb
"Do not disturb":"No molestar","Turn off Do not disturb":"Desactivar No molestar","For 1 hour":"Durante 1 hora",
"Until tomorrow morning":"Hasta mañana por la mañana","Until I turn it off":"Hasta que lo desactive",
"During calendar events":"Durante eventos del calendario","On until you turn it off":"Activado hasta que lo desactives",
"On until %@":"Activado hasta las %@","On during your calendar event":"Activado durante tu evento del calendario",
"Do not disturb: no sounds, the island doesn't open by itself":"No molestar: sin sonidos y la isla no se abre sola",
"Automatically during calendar events":"Automáticamente durante eventos del calendario",
"Calendar access granted":"Acceso al calendario concedido",
"Coucou needs access to your calendars to see when you're in a meeting":"Coucou necesita acceso a tus calendarios para saber cuándo estás en una reunión",
"Allow calendar access…":"Permitir acceso al calendario…",
"No sounds, and the island doesn't open by itself: finished, failed and approval events only badge the pill. Also in the 🌙 menu on the island.":"Sin sonidos y la isla no se abre sola: lo terminado, los fallos y las aprobaciones solo marcan la pastilla. También en el menú 🌙 de la isla.",
# session timeline
"Timeline":"Cronología","Everything Claude did in this session, with times":"Todo lo que hizo Claude en esta sesión, con horas",
"Session started":"Sesión iniciada","You asked":"Preguntaste","Turn finished":"Turno terminado","Turn failed":"El turno falló",
"You allowed":"Permitiste","You always allowed":"Permitiste siempre","You denied":"Denegaste","Not answered in time":"Sin respuesta a tiempo",
"%lld files read":"%lld archivos leídos","%lld edits":"%lld cambios","%lld commands":"%lld comandos","%lld approvals":"%lld aprobaciones",
"Read":"Leyó","Edited":"Editó","Wrote":"Escribió","Ran":"Ejecutó","Searched":"Buscó","Searched the web":"Buscó en la web",
"Opened":"Abrió","Subagent":"Subagente","Nothing yet. Claude Code's steps for this session show up here.":"Nada todavía. Aquí aparecen los pasos de Claude Code en esta sesión.",
"Copied":"Copiado","Copy as Markdown":"Copiar como Markdown","Back to the diff":"Volver al diff",
# auto-approve
"Ask every time":"Preguntar siempre","Auto-allow low risk":"Permitir solo el riesgo bajo","Auto-allow low and medium risk":"Permitir riesgo bajo y medio",
"Auto-allowed":"Permitido automáticamente","In %@":"En %@","Auto-approve in this project (never high risk)":"Aprobar automáticamente en este proyecto (nunca riesgo alto)",
"Auto-approve (Claude Code)":"Aprobación automática (Claude Code)",
"Coucou can answer Allow for you, per project. High-risk requests always ask. Auto-allowed steps show in the session timeline.":"Coucou puede responder Permitir por ti, por proyecto. Las peticiones de riesgo alto siempre preguntan. Lo permitido automáticamente aparece en la cronología.",
"Projects appear here once Claude Code runs in them (or set it from ⚡ on an approval).":"Los proyectos aparecen aquí cuando Claude Code trabaja en ellos (o configúralo desde ⚡ en una aprobación).",
# phone alerts
"Phone alerts":"Avisos al móvil","Send approvals that wait 20 s to my phone":"Enviar al móvil las aprobaciones que esperan 20 s",
"Only when I'm away (screen locked or 2 min idle)":"Solo cuando no estoy (pantalla bloqueada o 2 min sin actividad)",
"Topic":"Tema","New":"Nuevo","Server":"Servidor","Send test":"Enviar prueba",
"Install the free ntfy app (iOS / Android), tap + and subscribe to this topic. The alert includes the project and the command: keep the topic private, or use your own ntfy server.":"Instala la app gratuita ntfy (iOS / Android), pulsa + y suscríbete a este tema. El aviso incluye el proyecto y el comando: mantén el tema en privado o usa tu propio servidor ntfy.",
"Claude Code needs you · %@":"Claude Code te necesita · %@","Coucou is connected":"Coucou está conectado",
"You'll get approvals here when you're away from the Mac.":"Aquí recibirás las aprobaciones cuando no estés en el Mac.",
# linear
"Add your Linear API key in Settings":"Añade tu clave de API de Linear en Ajustes","Can't reach Linear":"No se puede conectar con Linear",
"Linear didn't accept the comment":"Linear no aceptó el comentario","Connected · nothing assigned to you":"Conectado · no tienes nada asignado",
"Connected · %lld open issues":"Conectado · %lld issues abiertas","Assigned to you":"Asignadas a ti","Assigned to you · %lld":"Asignadas a ti · %lld",
"Nothing open is assigned to you.":"No tienes nada abierto asignado.","A Claude Code session is working on it":"Una sesión de Claude Code está trabajando en ella",
"Open in Linear":"Abrir en Linear","Copy branch name":"Copiar nombre de la rama","Copy identifier":"Copiar identificador",
"Personal API key  (lin_api_…)":"Clave de API personal  (lin_api_…)",
"Linear → Settings → Security & access → Personal API keys. Shows your open issues and links each Claude Code session to the issue in its branch name.":"Linear → Settings → Security & access → Personal API keys. Muestra tus issues abiertas y vincula cada sesión de Claude Code con la issue de su rama.",
"Posted to %@":"Publicado en %@","Posting…":"Publicando…","Post to %@":"Publicar en %@",
"Add this timeline as a comment on %@ · %@":"Añadir esta cronología como comentario en %@ · %@",
# inbox
"Review requested":"Te pidieron review","Mentioned you":"Te mencionaron","Assignment":"Asignación","New comment":"Comentario nuevo","Update":"Novedad",
"Inbox: nothing waiting for you":"Bandeja: nada pendiente","Inbox: %lld waiting for you":"Bandeja: %lld pendientes","Inbox":"Bandeja",
"Mark all read":"Marcar todo leído","Mark as read":"Marcar como leído",
"Nothing waiting for you. Review requests, mentions and assignments from GitHub and Linear show up here.":"Nada pendiente. Aquí aparecen las peticiones de review, menciones y asignaciones de GitHub y Linear.",
"Mochi tells me when someone needs me":"Mochi me avisa cuando alguien me necesita","GitHub (through gh)":"GitHub (con gh)",
"Reviews":"Reviews","Mentions":"Menciones","Assigned":"Asignaciones","Comments":"Comentarios","Other":"Otros",
"Checked every minute. New items make Mochi peek out (only a badge in Do not disturb); the 🔔 in the island lists them. Opening or dismissing one marks it read on GitHub / Linear.":"Se revisa cada minuto. Lo nuevo hace que Mochi se asome (solo una marca en No molestar); la 🔔 de la isla lo lista. Abrir o descartar algo lo marca como leído en GitHub / Linear.",
"%lld new notifications. Latest, %@":"%lld notificaciones nuevas. La última, %@","Mochi says it out loud":"Mochi lo dice en voz alta","Try it":"Probar",
"Payments, last 7 days":"Pagos, últimos 7 días","Last build: %@ · %@":"Último build: %@ · %@","Build took %@":"El build tardó %@",
# other providers
"Other provider":"Otro proveedor","Provider":"Proveedor","Invalid server address":"Dirección del servidor no válida",
"Add your %@ API key in Settings → Chat.":"Añade tu clave de API de %@ en Ajustes → Chat.",
"The provider answered with an error.":"El proveedor respondió con un error.",
"%@ isn't answering at %@. Is it running?":"%@ no responde en %@. ¿Está abierto?",
"The provider rejected the API key. Check it in Settings → Chat.":"El proveedor rechazó la clave de API. Revísala en Ajustes → Chat.",
"The provider doesn't know the model “%@”. Pick another in Settings → Chat (Load models).":"El proveedor no conoce el modelo “%@”. Elige otro en Ajustes → Chat (Cargar modelos).",
"The provider is rate limiting this key. Wait a moment and try again.":"El proveedor está limitando esta clave. Espera un momento y vuelve a intentarlo.",
"The provider answered with an error (%lld).":"El proveedor respondió con un error (%lld).",
"Server address. Leave empty to use the default shown in grey.":"Dirección del servidor. Déjala vacía para usar la de gris.",
"API key":"Clave de API","API key (%@)":"Clave de API (%@)","Model (%@)":"Modelo (%@)","Pick":"Elegir","Loading…":"Cargando…","Load models":"Cargar modelos",
"The server returned no models.":"El servidor no devolvió modelos.",
"Mochi's chat goes to %@ with your key. Files and the code you're on are sent as text; edits and web search stay with the Claude engines.":"El chat de Mochi va a %@ con tu clave. Los archivos y el código se envían como texto; la edición y la búsqueda web siguen siendo de los motores de Claude.",
"Runs on your Mac: nothing leaves it. Start %@ first, then Load models.":"Funciona en tu Mac: nada sale de él. Abre primero %@ y luego Cargar modelos.",
# hook status
# Codex CLI (#44)
"Codex hooks installed":"Hooks de Codex instalados","Codex CLI not found":"No se encontró Codex CLI","Codex hooks not installed":"Hooks de Codex sin instalar",
"Run /hooks in Codex once to review and trust them. Codex sessions then show up next to Claude Code's.":"Ejecuta /hooks en Codex una vez para revisarlos y confiar en ellos. Después, las sesiones de Codex aparecen junto a las de Claude Code.",
"Install Codex CLI and run it once to see its sessions and approvals here too.":"Instala Codex CLI y ejecútalo una vez para ver aquí también sus sesiones y aprobaciones.",
"Coucou can follow Codex CLI sessions and approve them from the island. Codex is never blocked if Coucou isn't running.":"Coucou puede seguir las sesiones de Codex CLI y aprobarlas desde la isla. Codex nunca se bloquea si Coucou no está abierto.",
"Reinstall":"Reinstalar","Install Codex hooks":"Instalar hooks de Codex",
"deletes the file":"borra el archivo","+1 more file":"+1 archivo más","+%lld more files":"+%lld archivos más",
"Reinstall…":"Reinstalar…","Hooks installed, but out of date":"Hooks instalados, pero desactualizados","Hooks not installed":"Hooks sin instalar",
"Claude Code sessions, approvals and plan usage are connected to Coucou.":"Las sesiones de Claude Code, las aprobaciones y el uso del plan están conectados a Coucou.",
"Update them to get the latest: approvals that don't time out, plan usage bars.":"Actualízalos para tener lo último: aprobaciones sin tiempo agotado y barras de uso del plan.",
"Install them so Coucou sees your Claude Code sessions and can approve from the island. Claude Code is never blocked if Coucou isn't running.":"Instálalos para que Coucou vea tus sesiones de Claude Code y puedas aprobar desde la isla. Claude Code nunca se bloquea si Coucou no está abierto.",
"Coucou will write this to ~/.claude/settings.json (your current file is backed up first). Review it, then confirm.":"Coucou escribirá esto en ~/.claude/settings.json (antes guarda una copia del archivo actual). Revísalo y confirma.",
# hey mochi
"Needs Microphone and Speech Recognition (Allow now… above)":"Necesita Micrófono y Reconocimiento de voz (Permitir ahora… arriba)",
"This Mac can't recognize speech on-device in this language, so it stays off":"Este Mac no puede reconocer voz en el propio equipo en este idioma, así que queda desactivado",
"Paused: Do not disturb":"En pausa: No molestar","Paused: screen locked":"En pausa: pantalla bloqueada","Paused: on battery":"En pausa: con batería",
"Hey Mochi: start by voice, without the shortcut":"Oye Mochi: empezar con la voz, sin el atajo","Only when the Mac is plugged in":"Solo con el Mac enchufado",
"Listening for “Hey Mochi” (or “Oye Mochi”) on this Mac only. macOS shows the orange microphone dot while it listens.":"Escuchando “Oye Mochi” (o “Hey Mochi”) solo en este Mac. macOS muestra el punto naranja del micrófono mientras escucha.",
# updates
"Couldn't check for updates (%lld)":"No se pudo buscar actualizaciones (%lld)","Coucou %@ is available · Settings → Updates":"Coucou %@ está disponible · Ajustes → Actualizaciones",
"Coucou %@ is available (you have %@)":"Coucou %@ está disponible (tienes la %@)","Coucou %@":"Coucou %@","up to date":"al día",
"Checking…":"Comprobando…","Check now":"Comprobar ahora","Download the DMG":"Descargar el DMG","Install and restart":"Instalar y reiniciar","Downloading…":"Descargando…","Checking the signature…":"Comprobando la firma…","Restarting…":"Reiniciando…","Coucou updates itself and opens again in a few seconds.":"Coucou se actualiza solo y se vuelve a abrir en unos segundos.","The download isn't signed by Coucou's key. Nothing was installed.":"La descarga no está firmada con la clave de Coucou. No se instaló nada.","The downloaded app isn't the expected Coucou version. Nothing was installed.":"La app descargada no es la versión esperada de Coucou. No se instaló nada.","Open the release page":"Abrir la página de la versión",
"Open it and drag Coucou to Applications, replacing this one.":"Ábrelo y arrastra Coucou a Aplicaciones, reemplazando esta.",
"Check for updates automatically (every 6 hours, GitHub releases)":"Buscar actualizaciones automáticamente (cada 6 horas, en GitHub)","Updates":"Actualizaciones",
# whaticket
"Accepted · %@":"Aceptado · %@","Couldn't accept · %@":"No se pudo aceptar · %@","New ticket · %@":"Ticket nuevo · %@","Message · %@":"Mensaje · %@",
"Signed in as %@":"Sesión iniciada como %@","none":"ninguna",
"Waiting %lld · Mine %lld":"En espera %lld · Míos %lld","No tickets waiting.":"No hay tickets esperando.",
"Accept":"Aceptar","%lld new":"%lld nuevos",
"Auto-accept new tickets as me as soon as they arrive":"Aceptar a mi nombre los tickets nuevos en cuanto llegan",
"Only from these queues (none ticked = any of yours)":"Solo de estas colas (ninguna marcada = cualquiera de las tuyas)",
"Only between":"Solo entre","Any time — or e.g. 09:00-18:00":"A cualquier hora — o p. ej. 09:00-18:00",
"Can't reach %@ · %@":"No se puede conectar con %@ · %@",
"Coucou reads your whaticket.com queue through a small Chrome / Edge extension that uses the session you already have open — no token, no password, and it never signs you out.":"Coucou lee tu cola de whaticket.com con una pequeña extensión de Chrome / Edge que usa la sesión que ya tienes abierta: sin token, sin contraseña, y nunca te cierra la sesión.",
"Set up browser extension":"Configurar la extensión del navegador","Set up again":"Configurar de nuevo","Show folder":"Mostrar carpeta",
"Ready for %@. Extension folder: %@":"Lista para %@. Carpeta de la extensión: %@",
"1. Click Set up browser extension.":"1. Haz clic en Configurar la extensión del navegador.",
"2. In Chrome open chrome://extensions (in Edge: edge://extensions) and turn on Developer mode.":"2. En Chrome abre chrome://extensions (en Edge: edge://extensions) y activa el Modo de desarrollador.",
"3. Click Load unpacked and pick the extension folder shown above.":"3. Haz clic en Cargar descomprimida y elige la carpeta de la extensión que aparece arriba.",
"4. Keep a whaticket.com tab open, and turn on the WhaTicket pill under Integrations.":"4. Deja una pestaña de whaticket.com abierta y activa la píldora de WhaTicket en Integraciones.",
"Your queues show here once whaticket.com is open with the extension.":"Tus colas aparecen aquí cuando whaticket.com esté abierto con la extensión.",
"Only while your whaticket.com tab is open. Never during Do not disturb, never group chats, never tickets an AI agent is handling. Coucou only assigns the ticket — it never writes to the customer.":"Solo mientras tu pestaña de whaticket.com esté abierta. Nunca en No molestar, nunca chats de grupo, nunca tickets que atiende un agente de IA. Coucou solo se asigna el ticket: nunca le escribe al cliente.",
"Open whaticket.com in Chrome or Edge":"Abre whaticket.com en Chrome o Edge",
"Sign in to whaticket.com in Chrome or Edge.":"Inicia sesión en whaticket.com en Chrome o Edge.",
"whaticket.com's session expired: use the tab once (or sign in again).":"La sesión de whaticket.com expiró: usa la pestaña una vez (o vuelve a iniciar sesión).",
"Open whaticket.com in Chrome or Edge (with the Coucou extension) to accept from here.":"Abre whaticket.com en Chrome o Edge (con la extensión de Coucou) para aceptar desde aquí.",
"No Chrome, Edge, Brave or Chromium found for this user":"No se encontró Chrome, Edge, Brave ni Chromium para este usuario",
"This build of Coucou doesn't include the browser extension.":"Esta versión de Coucou no incluye la extensión del navegador.",
"The browser extension isn't available in the App Store version.":"La extensión del navegador no está disponible en la versión de la App Store.",
"Unknown ticket":"Ticket desconocido","Someone already took that ticket.":"Alguien ya tomó ese ticket.",
# google
"Google":"Google","Gmail":"Gmail","Connect Google…":"Conectar Google…","Finish signing in in your browser…":"Termina de iniciar sesión en tu navegador…",
"Disconnect":"Desconectar","Connected.":"Conectado.","Connected as %@.":"Conectado como %@.","Gmail shows":"Gmail muestra",
"Client ID  (….apps.googleusercontent.com)":"ID de cliente  (….apps.googleusercontent.com)","Client secret  (GOCSPX-…)":"Secreto del cliente  (GOCSPX-…)",
"Gmail in the island and your Drive files in the chat (type @ and a file name). Read-only: Coucou never sends mail or changes files.":"Gmail en la isla y tus archivos de Drive en el chat (escribe @ y el nombre de un archivo). Solo lectura: Coucou nunca envía correos ni cambia archivos.",
"One-time setup, free: in console.cloud.google.com create a project, turn on the Gmail API and the Google Drive API, set up the OAuth consent screen (External, add yourself as a test user, then Publish it so the sign-in doesn't expire every 7 days), and create an OAuth client ID of type \"Desktop app\". Paste its ID and secret here.":"Configuración única y gratuita: en console.cloud.google.com crea un proyecto, activa la API de Gmail y la de Google Drive, configura la pantalla de consentimiento OAuth (Externa, agrégate como usuario de prueba y luego Publícala para que la sesión no caduque cada 7 días) y crea un ID de cliente OAuth de tipo \"App de escritorio\". Pega aquí su ID y su secreto.",
"A Gmail search, e.g. is:unread in:inbox, or is:important is:unread. Turn on the Gmail pill under Integrations.":"Una búsqueda de Gmail, p. ej. is:unread in:inbox o is:important is:unread. Activa la píldora de Gmail en Integraciones.",
"Unread · %lld":"Sin leer · %lld","Inbox":"Bandeja","Nothing new in your inbox.":"Nada nuevo en tu bandeja.","(no subject)":"(sin asunto)","Ask":"Preguntar",
"Mail · %@":"Correo · %@","Ask me anything… (/ skills, @ Drive)":"Pregúntame lo que quieras… (/ skills, @ Drive)",
"Searching Drive…":"Buscando en Drive…","Downloading…":"Descargando…","No Drive file with that name.":"Ningún archivo de Drive con ese nombre.",
"Connect Google in Settings → Google to search your Drive.":"Conecta Google en Ajustes → Google para buscar en tu Drive.",
"Sheet":"Hoja","Doc":"Documento","Slides":"Presentación",
"Couldn't open a local port for the sign-in.":"No se pudo abrir un puerto local para iniciar sesión.",
"Nobody finished signing in within 5 minutes.":"Nadie terminó de iniciar sesión en 5 minutos.",
"Paste your Google OAuth client ID first (see the steps above).":"Pega primero tu ID de cliente OAuth de Google (mira los pasos de arriba).",
"No code from Google":"Google no envió ningún código","Google said: %@":"Google dijo: %@",
"The answer from Google didn't match this sign-in.":"La respuesta de Google no corresponde a este inicio de sesión.",
"Google sent no refresh token":"Google no envió un token de actualización","Can't reach Google":"No se puede conectar con Google",
"Google refused the sign-in (%lld) %@":"Google rechazó el inicio de sesión (%lld) %@","Not connected to Google":"No conectado a Google",
"Google signed Coucou out — connect again in Settings":"Google cerró la sesión de Coucou: vuelve a conectar en Ajustes",
"Google refused (403): is the Gmail / Drive API turned on in your Google Cloud project?":"Google lo rechazó (403): ¿está activada la API de Gmail / Drive en tu proyecto de Google Cloud?",
"Google error %lld":"Error de Google %lld","That file is over 10 MB — too big for the chat.":"Ese archivo pasa de 10 MB: demasiado grande para el chat.",
"Coucou can read Docs, Sheets, Slides and ordinary files — not this kind.":"Coucou puede leer Documentos, Hojas, Presentaciones y archivos normales, pero no este tipo.",
# skills
"Skills":"Skills","Personal":"Personal","Codex":"Codex","Project · %@":"Proyecto · %@","Plugin · %@":"Plugin · %@",
"What Claude Code and Codex can use on this Mac: your own skills, each project's, and the ones that come with plugins. Turning one off moves it aside; nothing is deleted.":"Lo que Claude Code y Codex pueden usar en este Mac: tus skills, las de cada proyecto y las que vienen con plugins. Apagar una la aparta; no se borra nada.",
"Search skills…":"Buscar skills…","No skills on this Mac yet. Add one below.":"Aún no hay skills en este Mac. Agrega una abajo.",
"Add a skill":"Agregar una skill","Install to":"Instalar en","Folder, .zip / .skill file, or a GitHub link":"Carpeta, archivo .zip / .skill o un enlace de GitHub",
"Choose…":"Elegir…","Looking…":"Buscando…","Preview":"Vista previa",
"Or drop a skill folder or a .zip / .skill file here. You see what's inside before anything is installed.":"O suelta aquí una carpeta de skill o un archivo .zip / .skill. Ves lo que contiene antes de instalar nada.",
"New skill name":"Nombre de la nueva skill","Create":"Crear","scripts":"scripts","off":"apagada","No description.":"Sin descripción.",
"Hide":"Ocultar","View":"Ver","Open in the editor":"Abrir en el editor","Folder":"Carpeta","SKILL.md can't be read":"No se puede leer SKILL.md",
"%lld files: %@%@":"%lld archivos: %@%@","Installs to %@":"Se instala en %@",
"It has scripts. Coucou never runs them, but Claude may when it uses the skill — read them first.":"Tiene scripts. Coucou nunca los ejecuta, pero Claude puede hacerlo al usar la skill: revísalos antes.",
"A skill with this name is already there; installing replaces it (the old one is kept in Coucou's trash).":"Ya hay una skill con este nombre; instalar la reemplaza (la anterior se guarda en la papelera de Coucou).",
"Install %lld skills":"Instalar %lld skills","Install":"Instalar","Cancel":"Cancelar",
"Installed. Claude Code picks it up in its next session.":"Instalada. Claude Code la usará desde su próxima sesión.",
"Choose a skill folder, or a .zip / .skill file":"Elige una carpeta de skill o un archivo .zip / .skill",
"The archive tries to write outside its folder.":"El archivo intenta escribir fuera de su carpeta.","The archive couldn't be opened.":"No se pudo abrir el archivo comprimido.",
"Claude Code — personal (~/.claude/skills)":"Claude Code — personal (~/.claude/skills)","Codex (~/.codex/skills)":"Codex (~/.codex/skills)","Project — %@":"Proyecto — %@",
"There's already a skill with that folder name.":"Ya hay una skill con ese nombre de carpeta.","Pick where to install it.":"Elige dónde instalarla.",
"Only github.com links to a repository or a folder in one.":"Solo enlaces de github.com a un repositorio o a una carpeta dentro de uno.",
"GitHub answered %lld — check the link (public repos only).":"GitHub respondió %lld: revisa el enlace (solo repositorios públicos).",
"That repository is too big to be a skill (over 50 MB).":"Ese repositorio es demasiado grande para ser una skill (más de 50 MB).",
"Nothing there — check the path.":"No hay nada ahí: revisa la ruta.",
"Drop a skill folder, a .zip or .skill file, or paste a GitHub link.":"Suelta una carpeta de skill, un archivo .zip o .skill, o pega un enlace de GitHub.",
"No SKILL.md in there, so it isn't a skill.":"No contiene SKILL.md, así que no es una skill.","That preview expired — preview it again.":"Esa vista previa caducó: vuelve a generarla.",
"Pick where to create it.":"Elige dónde crearla.","A skill with that name already exists.":"Ya existe una skill con ese nombre.",
"Remove the skill":"Quitar la skill","What should it do?":"¿Qué debe hacer?","Ask me anything… (/ for skills)":"Pregúntame lo que quieras… (/ para skills)",
"No skill matches.":"Ninguna skill coincide.","No skills installed. Add some in Settings → Skills.":"No hay skills instaladas. Agrégalas en Ajustes → Skills.",
}
catalog = {"sourceLanguage": "en", "version": "1.0", "strings": {
    k: {"localizations": {"es": {"stringUnit": {"state": "translated", "value": v}}}} for k, v in sorted(ES.items())
}}
import os
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "NotchBuddy", "Resources", "Localizable.xcstrings")
with open(path, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
print(len(ES), "strings")
